namespace Lemmy.Enums {
  export type ListingType = 'All' | 'Local' | 'Subscribed'
  export type SortType =
    | 'Active'
    | 'Hot'
    | 'New'
    | 'Old'
    | 'TopDay'
    | 'TopWeek'
    | 'TopMonth'
    | 'TopYear'
    | 'TopAll'
    | 'MostComments'
    | 'NewComments'
    | 'TopHour'
    | 'TopSixHour'
    | 'TopTwelveHour'
    | 'TopThreeMonths'
    | 'TopSixMonths'
    | 'TopNineMonths'
  export type CommentSortType = 'Hot' | 'Top' | 'New' | 'Old'
  export type SubscribedType = 'Subscribed' | 'NotSubscribed' | 'Pending'
  export type RegistrationMode = 'Open' | 'Closed' | 'RequireApplication'
  export type SearchType =
    | 'All'
    | 'Comments'
    | 'Communities'
    | 'Posts'
    | 'Url'
    | 'Users'
}
